title: <p align="center"> Kanhu Charan Mishra </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kanhu-charan-mishra-bb062b126/">LinkedIn</a> |
  <a href="https://github.com/kanhu123mishra">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time data.
  Worked with Deloitte USI in the Data Engineering team.
  Working in Retail domain for 5+ years.
  <br>
  </p>



theme: jekyll-theme-minimal
